// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeDeletePath(arg1) {
  return window['go']['main']['App']['AnalyzeDeletePath'](arg1);
}

export function AnalyzeGetLargeFiles(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeGetLargeFiles'](arg1, arg2);
}

export function AnalyzeOpenInFinder(arg1) {
  return window['go']['main']['App']['AnalyzeOpenInFinder'](arg1);
}

export function AnalyzeScanDirectory(arg1) {
  return window['go']['main']['App']['AnalyzeScanDirectory'](arg1);
}

export function CleanExecute(arg1, arg2) {
  return window['go']['main']['App']['CleanExecute'](arg1, arg2);
}

export function CleanGetWhitelist() {
  return window['go']['main']['App']['CleanGetWhitelist']();
}

export function CleanScanTargets() {
  return window['go']['main']['App']['CleanScanTargets']();
}

export function CleanUpdateWhitelist(arg1) {
  return window['go']['main']['App']['CleanUpdateWhitelist'](arg1);
}

export function OptimizeExecute(arg1) {
  return window['go']['main']['App']['OptimizeExecute'](arg1);
}

export function OptimizeGetTasks() {
  return window['go']['main']['App']['OptimizeGetTasks']();
}

export function OptimizeGetWhitelist() {
  return window['go']['main']['App']['OptimizeGetWhitelist']();
}

export function OptimizeUpdateWhitelist(arg1) {
  return window['go']['main']['App']['OptimizeUpdateWhitelist'](arg1);
}

export function StatusGetMetrics() {
  return window['go']['main']['App']['StatusGetMetrics']();
}

export function StatusStartMonitoring(arg1) {
  return window['go']['main']['App']['StatusStartMonitoring'](arg1);
}

export function StatusStopMonitoring() {
  return window['go']['main']['App']['StatusStopMonitoring']();
}

export function TouchIDDisable() {
  return window['go']['main']['App']['TouchIDDisable']();
}

export function TouchIDEnable() {
  return window['go']['main']['App']['TouchIDEnable']();
}

export function TouchIDGetStatus() {
  return window['go']['main']['App']['TouchIDGetStatus']();
}

export function UninstallApps(arg1) {
  return window['go']['main']['App']['UninstallApps'](arg1);
}

export function UninstallGetRelatedFiles(arg1) {
  return window['go']['main']['App']['UninstallGetRelatedFiles'](arg1);
}

export function UninstallScanApps(arg1) {
  return window['go']['main']['App']['UninstallScanApps'](arg1);
}
