// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AnalyzeDeletePath(arg1:string):Promise<void>;

export function AnalyzeGetLargeFiles(arg1:string,arg2:number):Promise<Array<models.FileEntry>>;

export function AnalyzeOpenInFinder(arg1:string):Promise<void>;

export function AnalyzeScanDirectory(arg1:string):Promise<models.ScanResult>;

export function CleanExecute(arg1:Array<string>,arg2:boolean):Promise<void>;

export function CleanGetWhitelist():Promise<Array<string>>;

export function CleanScanTargets():Promise<Array<models.CleanCategory>>;

export function CleanUpdateWhitelist(arg1:Array<string>):Promise<void>;

export function OptimizeExecute(arg1:Array<string>):Promise<void>;

export function OptimizeGetTasks():Promise<Array<models.OptimizationTask>>;

export function OptimizeGetWhitelist():Promise<Array<string>>;

export function OptimizeUpdateWhitelist(arg1:Array<string>):Promise<void>;

export function PurgeExecute(arg1:Array<string>):Promise<void>;

export function PurgeScanProjects(arg1:string):Promise<Array<models.Project>>;

export function StatusGetMetrics():Promise<models.MetricsSnapshot>;

export function StatusStartMonitoring(arg1:number):Promise<void>;

export function StatusStopMonitoring():Promise<void>;

export function TouchIDDisable():Promise<void>;

export function TouchIDEnable():Promise<void>;

export function TouchIDGetStatus():Promise<models.TouchIDStatus>;

export function UninstallApps(arg1:Array<string>):Promise<void>;

export function UninstallGetRelatedFiles(arg1:string):Promise<Array<string>>;

export function UninstallScanApps(arg1:boolean):Promise<Array<models.Application>>;
